title: SoilFER Integrated soil information for decision-making

lsi: false
safe: true
source: SoilFER-TM
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

domain: fao-gsp.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://fao-gsp.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /GSNmap-TM/      # place folder name if the site is served in a subfolder
